### ISSUE TITLE
Why a module vs a class?

### ISSUE THREAD

**Issue by Maikon** [eatoncns/ttt_web#8]
https://github.com/eatoncns/ttt_web/blob/757a38bf60e23dc7b3a038f1ecef3cc4cdec730d/lib/game_mode.rb#L6

What's the reasoning for using a module here and for prepending the method with the name of it?

**Comment by eatoncns** [comment]
I used a module here as all I really needed was namespacing for the function. I could have used a class with class method but to me that adds some extra semantic baggage (possibility of inheritance etc.) that wasn't necessary.

Regarding prepending the name: is there another way of doing it? The method didn't seem to be visible outside of the module without it.

**Comment by Maikon** [comment]
Looking at the code, I see you found `self` 👍  The other common way with modules is including them and then calling the method directly without prepending it.

_"adds some extra semantic baggage"_ - That could be said for every class though. Just because we have a class, it doesn't mean we intentionally did so for inheritance purposes 🙂

**Comment by eatoncns** [comment]
You are right, inheritance was a bad example. 

More generally to me a class means state to encapsulate, otherwise it is really just a function. We then get to namespacing functions. In C++ for example we have an explicit namespace keyword, in Java packages. I was looking for the equivalent in ruby. If it is idiomatic to have a class containing only class functions then I will go that way.

In any case GameMode is now a class so I will close the issue :)
